const columns=['Backlog','In progress','In review','Done'];
let tasks=JSON.parse(localStorage.getItem('codexOpsTasks')||'null')||[],runs=[],interactiveRuns=[],cliSessions=[],codexProcesses=[],priorityFilter='all';
const board=document.querySelector('#boardColumns'),runGrid=document.querySelector('#runGrid');
const escapeHtml=text=>{const p=document.createElement('p');p.textContent=text??'';return p.innerHTML};
const elapsed=(start,end)=>{const seconds=Math.max(0,Math.floor(((end?new Date(end):new Date())-new Date(start))/1000));return `${Math.floor(seconds/60)}m ${String(seconds%60).padStart(2,'0')}s`};
function taskHtml(task){return `<article class="task"><span class="task-label label-${task.type}">${task.tag}</span><h3>${escapeHtml(task.title)}</h3><div class="task-bottom"><span class="ticket">${task.id}</span><span class="priority ${task.priority}"></span><span class="assignee ${task.color}">${task.initials}</span></div></article>`}
function renderBoard(query=''){const value=query.toLowerCase();board.innerHTML=columns.map(column=>{const items=tasks.filter(task=>task.column===column&&`${task.title} ${task.id}`.toLowerCase().includes(value)&&(priorityFilter==='all'||task.priority===priorityFilter));return `<div class="column"><div class="column-head"><strong>${column}</strong><span>${items.length}</span></div><div class="task-list">${items.map(taskHtml).join('')}</div>${column==='Backlog'?'<button class="add-task" id="addFromBoard">+ Add task</button>':''}</div>`}).join('');document.querySelector('#taskCount').textContent=tasks.length;const add=document.querySelector('#addFromBoard');if(add)add.onclick=()=>document.querySelector('#taskModal').showModal()}
function runHtml(run){const last=run.events?.at(-1),message=last?last.message:'Waiting for Codex to begin...';const transcript=run.source==='interactive CLI',details=`<button class="more" data-details="${run.id}" aria-label="View ${transcript?'CLI transcript':'run details'}">${transcript?'Transcript':'Details'}</button>`,action=run.status==='running'?(transcript?`${details}<button class="stop-run" data-stop="${run.id}">Stop</button>`:`<button class="stop-run" data-stop="${run.id}">Stop</button>`):details;return `<article class="agent-card run-card ${run.status}"><div class="agent-top"><div class="agent-avatar ${run.status==='failed'?'coral':'violet'}">CMD</div><div class="agent-name"><strong>${escapeHtml(run.name)}</strong><span class="run-status"><i class="status-dot"></i> ${run.status} · ${elapsed(run.startedAt,run.endedAt)}</span></div>${action}</div><div class="command"><span>$</span> ${escapeHtml(run.workdir)}</div><div class="agent-footer"><small class="event-line">${escapeHtml(message)}</small></div></article>`}
function activityById(id){return [...runs,...interactiveRuns,...cliSessions].find(item=>item.id===id)}
async function showDetails(id){const run=activityById(id);if(!run)return;const modal=document.querySelector('#detailsModal'),title=document.querySelector('#detailsTitle'),content=document.querySelector('#detailsContent'),followUp=document.querySelector('#followUpForm');title.textContent=run.source==='interactive CLI'?(run.name||'CLI transcript'):(run.name||'Run details');followUp.hidden=run.source!=='interactive CLI';followUp.dataset.sessionId=run.threadId||'';content.textContent='Loading local activity...';modal.showModal();if(run.source==='interactive CLI'&&run.threadId){try{const response=await fetch(`/api/sessions/${encodeURIComponent(run.threadId)}/transcript`),result=await response.json();if(!response.ok)throw new Error(result.error);content.textContent=result.entries.length?result.entries.map(entry=>`[${entry.role.toUpperCase()}]\n${entry.text}`).join('\n\n'):'No user or agent messages have been written to this session yet.';return}catch(error){content.textContent=`Could not load this local transcript: ${error.message}`;return}}const details=[`Status: ${run.status}`,`Source: ${run.source||'dashboard run'}`,`Model: ${run.model||'CLI default'}`,`Working directory: ${run.workdir||'unknown'}`,`Started: ${run.startedAt||'unknown'}`,`Ended: ${run.endedAt||'still active'}`,run.prompt?`\nPrompt:\n${run.prompt}`:'','Recent activity:',...(run.events||[]).slice(-20).map(event=>`- ${event.message||JSON.stringify(event)}`)].join('\n');content.textContent=details}
function renderRuns(){const active=runs.filter(run=>run.status==='running'),display=[...cliSessions,...interactiveRuns,...active,...runs.filter(run=>run.status!=='running').slice(0,3)].slice(0,6);runGrid.innerHTML=display.length?display.map(runHtml).join(''):'<div class="empty-runs">No local runs yet. Start a Codex task or run the interactive CLI to see live progress here.</div>';document.querySelectorAll('[data-stop]').forEach(button=>button.onclick=async()=>{button.disabled=true;await fetch(`/api/runs/${button.dataset.stop}/stop`,{method:'POST'}).catch(()=>{});});document.querySelectorAll('[data-details]').forEach(button=>button.onclick=()=>showDetails(button.dataset.details))}
function mergeRun(run){const index=runs.findIndex(item=>item.id===run.id);if(index===-1)runs.unshift(run);else runs[index]={...runs[index],...run};renderRuns()}
function updateMonitor(state){const connected=state.status==='connected',standby=state.status==='standby',count=(state.threads||[]).length;document.querySelector('#monitorStatus').classList.toggle('is-connected',connected||standby);document.querySelector('#monitorTitle').textContent=connected?(count?`${count} interactive session${count===1?'':'s'} connected`:'App-server connected - waiting for a task'):standby?'Local live tracking ready':'Interactive CLI not connected';document.querySelector('#monitorDetail').textContent=connected?'Start work in the Codex terminal and its live activity will appear below.':state.message||'Dashboard runs and normal local Codex CLI sessions are tracked live.'}
function updateProcessCount(state){codexProcesses=state.processes||[];const count=codexProcesses.length;document.querySelector('#processCount').textContent=String(count);document.querySelector('#monitorProcessCount').textContent=`${count} process${count===1?'':'es'}`;document.querySelector('#monitorUsageText').textContent=count?'Codex executable processes currently visible':'No Codex executable process is currently visible';document.querySelector('#monitorMeter').style.width=`${Math.min(count*8,100)}%`}
renderBoard();
document.querySelector('#openModal').onclick=()=>document.querySelector('#taskModal').showModal();
document.querySelector('#openRunModal').onclick=()=>document.querySelector('#runModal').showModal();
document.querySelector('#closeDetails').onclick=()=>document.querySelector('#detailsModal').close();
document.querySelector('#detailsDone').onclick=()=>document.querySelector('#detailsModal').close();
document.querySelector('#followUpForm').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,prompt=document.querySelector('#followUpPrompt').value.trim(),button=document.querySelector('#sendFollowUp');if(!prompt||!form.dataset.sessionId)return;button.disabled=true;button.textContent='Sending...';try{const response=await fetch(`/api/sessions/${encodeURIComponent(form.dataset.sessionId)}/follow-up`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt})}),run=await response.json();if(!response.ok)throw new Error(run.error);mergeRun(run);document.querySelector('#detailsContent').textContent+=`\n\n[USER]\n${prompt}\n\nFollow-up started. Its live progress is now on the activity board.`;document.querySelector('#followUpPrompt').value=''}catch(error){alert(`Could not send follow-up: ${error.message}`)}finally{button.disabled=false;button.textContent='Send follow-up'}});
document.querySelector('#search').addEventListener('input',event=>renderBoard(event.target.value));
document.querySelector('#filterButton').onclick=()=>{const filters=['all','high','medium','low'];priorityFilter=filters[(filters.indexOf(priorityFilter)+1)%filters.length];document.querySelector('#filterButton').textContent=priorityFilter==='all'?'All priorities':`${priorityFilter[0].toUpperCase()}${priorityFilter.slice(1)} priority`;renderBoard(document.querySelector('#search').value)};
document.querySelector('#refreshButton').onclick=()=>window.location.reload();
document.querySelector('#taskForm').addEventListener('submit',event=>{event.preventDefault();const title=document.querySelector('#taskTitle').value.trim();if(!title)return;const agent=document.querySelector('#taskAgent').value,initials=agent==='Unassigned'?'--':agent.split('-').map(word=>word[0]).join('').toUpperCase(),color=agent==='api-migrations'?'teal':agent==='release-qa'?'gold':agent==='frontend-refactor'?'coral':'purple';tasks.unshift({title,tag:'FEATURE',type:'feature',id:`COD-${143+tasks.length}`,priority:document.querySelector('#taskPriority').value,initials,color,column:'Backlog'});localStorage.setItem('codexOpsTasks',JSON.stringify(tasks));renderBoard(document.querySelector('#search').value);document.querySelector('#taskModal').close();event.target.reset()});
document.querySelector('#runForm').addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter;button.disabled=true;button.textContent='Starting...';try{const response=await fetch('/api/runs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:document.querySelector('#runName').value,model:document.querySelector('#runModel').value,prompt:document.querySelector('#runPrompt').value,workdir:document.querySelector('#runWorkdir').value})}),result=await response.json();if(!response.ok)throw new Error(result.error);mergeRun(result);document.querySelector('#runModal').close();event.target.reset()}catch(error){alert(`Could not start Codex: ${error.message}`)}finally{button.disabled=false;button.textContent='Start Codex'}});
fetch('/api/runs').then(response=>response.json()).then(items=>{runs=items;renderRuns()}).catch(()=>{});
fetch('/api/interactive').then(response=>response.json()).then(state=>{interactiveRuns=state.threads||[];renderRuns();updateMonitor(state)}).catch(()=>{});
fetch('/api/sessions').then(response=>response.json()).then(state=>{cliSessions=state.sessions||[];renderRuns()}).catch(()=>{});
fetch('/api/processes').then(response=>response.json()).then(updateProcessCount).catch(()=>{});
const stream=new EventSource('/events'),connection=document.querySelector('#connection');
stream.onopen=()=>{connection.textContent='Local tracker connected';connection.classList.add('connected')};
stream.onerror=()=>{connection.textContent='Reconnecting...';connection.classList.remove('connected')};
stream.addEventListener('run',event=>mergeRun(JSON.parse(event.data)));
stream.addEventListener('event',event=>{const {runId,entry,eventCount}=JSON.parse(event.data),run=runs.find(item=>item.id===runId);if(run){run.events=[...(run.events||[]),entry].slice(-80);run.eventCount=eventCount;renderRuns()}});
stream.addEventListener('interactive',event=>{const state=JSON.parse(event.data);interactiveRuns=state.threads||[];renderRuns();updateMonitor(state)});
stream.addEventListener('sessions',event=>{cliSessions=(JSON.parse(event.data).sessions)||[];renderRuns()});
stream.addEventListener('processes',event=>updateProcessCount(JSON.parse(event.data)));
setInterval(()=>{if(runs.some(run=>run.status==='running'))renderRuns()},1000);
