const http = require('http');
const fs = require('fs');
const path = require('path');
const { spawn, execFile } = require('child_process');
const root = __dirname, allowedRoot = path.resolve(path.join(root, '..'));
const codexBin = process.env.CODEX_BIN || (process.platform === 'win32' ? path.join(process.env.LOCALAPPDATA || '', 'Programs', 'OpenAI', 'Codex', 'bin', 'codex.exe') : 'codex');
const clients = new Set(), runs = new Map();
const interactive = { status: 'standby', message: 'Dashboard-launched runs and normal Codex CLI sessions are tracked live.', threads: [] };
const send = (res, status, body, type = 'application/json') => { res.writeHead(status, { 'Content-Type': type, 'Cache-Control': 'no-store' }); res.end(type === 'application/json' ? JSON.stringify(body) : body); };
const broadcast = (event, data) => { const message = `event: ${event}\ndata: ${JSON.stringify(data)}\n\n`; clients.forEach(client => client.write(message)); };
const publicRun = ({ process, ...run }) => run;
function safeWorkdir(input) { const resolved = path.resolve(input || allowedRoot); if (resolved !== allowedRoot && !resolved.startsWith(allowedRoot + path.sep)) throw new Error('Working directory must be inside your Desktop folder.'); if (!fs.existsSync(resolved) || !fs.statSync(resolved).isDirectory()) throw new Error('Working directory does not exist.'); return resolved; }
function summarize(event) { const type = event.type || 'event', item = event.item || {}; if (type.includes('command_execution')) return item.command || event.command || 'Running shell command'; if (type.includes('agent_message')) return (item.text || event.text || 'Agent update').slice(0, 180); if (type.includes('file_change')) return 'Updating workspace files'; if (type.includes('error')) return event.message || 'Codex reported an error'; return type.replaceAll('_', ' '); }
function startRun({ prompt, name, workdir, model }) {
  if (!prompt || typeof prompt !== 'string') throw new Error('A task prompt is required.');
  const id = `run-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 6)}`;
  const selectedModel = typeof model === 'string' && /^[a-z0-9.-]{1,80}$/i.test(model) ? model : null;
  const run = { id, name: (name || 'codex-agent').slice(0, 48), prompt: prompt.slice(0, 8000), workdir: safeWorkdir(workdir), model: selectedModel || 'CLI default', status: 'running', source: 'dashboard', startedAt: new Date().toISOString(), endedAt: null, events: [], eventCount: 0, pid: null };
  const args = ['exec', '--json', '--skip-git-repo-check', '-C', run.workdir]; if (selectedModel) args.push('-m', selectedModel); args.push(prompt);
  const child = spawn(codexBin, args, { windowsHide: true, stdio: ['ignore', 'pipe', 'pipe'] });
  run.process = child; run.pid = child.pid; runs.set(id, run); broadcast('run', publicRun(run)); let pending = '';
  child.stdout.setEncoding('utf8'); child.stdout.on('data', chunk => { pending += chunk; const lines = pending.split(/\r?\n/); pending = lines.pop(); for (const line of lines) { if (!line.trim()) continue; let parsed; try { parsed = JSON.parse(line); } catch { parsed = { type: 'stdout', text: line }; } const entry = { at: new Date().toISOString(), type: parsed.type || 'event', message: summarize(parsed), raw: parsed }; run.events.push(entry); run.events = run.events.slice(-80); run.eventCount++; broadcast('event', { runId: id, entry, eventCount: run.eventCount }); } });
  child.stderr.setEncoding('utf8'); child.stderr.on('data', chunk => { const entry = { at: new Date().toISOString(), type: 'stderr', message: chunk.trim().slice(0, 400) }; if (entry.message) { run.events.push(entry); broadcast('event', { runId: id, entry, eventCount: run.eventCount }); } });
  child.on('error', error => { run.status = 'failed'; run.error = error.message; run.endedAt = new Date().toISOString(); broadcast('run', publicRun(run)); }); child.on('close', code => { run.status = code === 0 ? 'completed' : 'failed'; run.exitCode = code; run.endedAt = new Date().toISOString(); broadcast('run', publicRun(run)); }); return publicRun(run);
}
function iso(seconds) { return typeof seconds === 'number' ? new Date(seconds * 1000).toISOString() : new Date().toISOString(); }
function publishInteractive() { broadcast('interactive', interactive); }
function displayThread(thread) { const status = thread.status?.type === 'active' ? 'running' : 'idle'; return { id: `cli-${thread.id}`, threadId: thread.id, name: thread.name || thread.preview || 'interactive-codex', workdir: thread.cwd || 'Local Codex session', source: 'interactive CLI', status, startedAt: iso(thread.createdAt), endedAt: status === 'idle' ? iso(thread.updatedAt) : null, events: [{ message: thread.preview || `Thread is ${status}` }], eventCount: 0 }; }
class AppServerBridge {
  constructor() { this.child = null; this.socket = null; this.buffer = ''; this.requestId = 100; this.pending = new Map(); this.timer = null; this.retry = null; this.remoteUrl = process.env.CODEX_APP_SERVER_URL; if (this.remoteUrl) this.connect(); else this.setState('standby', interactive.message); }
  setState(status, message) { interactive.status = status; interactive.message = message; publishInteractive(); }
  ready() { this.rpc('initialize', { clientInfo: { name: 'codex-command-center', version: '1.0.0' }, capabilities: { experimentalApi: true } }).then(() => { this.setState('connected', 'Watching interactive Codex CLI sessions'); this.poll(); this.timer = setInterval(() => this.poll(), 2000); }).catch(error => this.failed(error.message)); }
  connect() {
    if (this.child || this.socket) return; this.setState('connecting', this.remoteUrl ? 'Connecting to foreground Codex app-server…' : 'Connecting to local Codex app-server…');
    if (this.remoteUrl) { try { const socket = this.socket = new WebSocket(this.remoteUrl); socket.onopen = () => this.ready(); socket.onmessage = event => this.read(String(event.data), true); socket.onerror = () => this.failed('Could not reach foreground app-server.'); socket.onclose = () => this.failed('Foreground app-server stopped.'); } catch (error) { this.failed(error.message); } return; }
    try { this.child = spawn(codexBin, ['app-server', 'proxy'], { windowsHide: true, stdio: ['pipe', 'pipe', 'pipe'] }); } catch (error) { this.failed(error.message); return; }
    this.child.stdout.setEncoding('utf8'); this.child.stdout.on('data', data => this.read(data)); this.child.stderr.setEncoding('utf8'); this.child.stderr.on('data', data => { if (data.trim()) this.failed(data.trim()); }); this.child.on('error', error => this.failed(error.message)); this.child.on('close', () => this.failed('Local app-server is not running.')); this.ready();
  }
  failed(message) { if (this.child) { this.child.removeAllListeners(); this.child = null; } if (this.socket) { this.socket.onclose = null; this.socket.close(); this.socket = null; } clearInterval(this.timer); this.timer = null; interactive.threads = []; this.setState('unavailable', message.replace(/^Error:\s*/i, '').slice(0, 180)); clearTimeout(this.retry); this.retry = setTimeout(() => this.connect(), 5000); }
  read(data, boundary = false) { if (boundary) { this.buffer += data; const line = this.buffer; this.buffer = ''; this.handle(line); return; } this.buffer += data; const lines = this.buffer.split(/\r?\n/); this.buffer = lines.pop(); lines.forEach(line => this.handle(line)); }
  handle(line) { if (!line.trim()) return; let message; try { message = JSON.parse(line); } catch { return; } if (message.id && this.pending.has(message.id)) { const { resolve, reject, timeout } = this.pending.get(message.id); clearTimeout(timeout); this.pending.delete(message.id); message.error ? reject(new Error(message.error.message || 'App-server request failed')) : resolve(message.result); } else if (message.method === 'thread/status/changed') this.poll(); }
  rpc(method, params) { return new Promise((resolve, reject) => { const usable = this.socket?.readyState === 1 || this.child?.stdin.writable; if (!usable) return reject(new Error('App-server connection unavailable')); const id = ++this.requestId, timeout = setTimeout(() => { this.pending.delete(id); reject(new Error('App-server did not respond')); }, 6000), payload = JSON.stringify({ jsonrpc: '2.0', id, method, params }); this.pending.set(id, { resolve, reject, timeout }); this.socket?.readyState === 1 ? this.socket.send(payload) : this.child.stdin.write(`${payload}\n`); }); }
  poll() { this.rpc('thread/list', { limit: 50, sourceKinds: ['cli'], sortKey: 'recency_at', sortDirection: 'desc', useStateDbOnly: true }).then(result => { interactive.threads = (result.data || []).filter(t => t.status?.type === 'active').map(displayThread); this.setState('connected', interactive.threads.length ? `Watching ${interactive.threads.length} interactive session${interactive.threads.length === 1 ? '' : 's'}` : 'Watching interactive Codex CLI sessions'); }).catch(error => this.failed(error.message)); }
}
new AppServerBridge();
const cliSessions = { sessions: [] }, sessionFiles = new Map();
const sessionRoot = path.join(process.env.USERPROFILE || '', '.codex', 'sessions');
function walkJsonl(dir, files = []) { try { for (const entry of fs.readdirSync(dir, { withFileTypes: true })) { const file = path.join(dir, entry.name); if (entry.isDirectory()) walkJsonl(file, files); else if (entry.name.endsWith('.jsonl')) files.push(file); } } catch {} return files; }
function readPart(file, position, length) { const fd = fs.openSync(file, 'r'); const buffer = Buffer.alloc(length); const bytes = fs.readSync(fd, buffer, 0, length, position); fs.closeSync(fd); return buffer.subarray(0, bytes).toString('utf8'); }
function jsonLines(text) { return text.split(/\r?\n/).map(line => { try { return JSON.parse(line); } catch { return null; } }).filter(Boolean); }
function sessionName(id) { try { const lines = fs.readFileSync(path.join(process.env.USERPROFILE || '', '.codex', 'session_index.jsonl'), 'utf8').trim().split(/\r?\n/); for (let i = lines.length - 1; i >= 0; i--) { const item = JSON.parse(lines[i]); if (item.id === id) return item.thread_name; } } catch {} return `CLI session ${id.slice(0, 8)}`; }
function scanSessions() {
  const cutoff = Date.now() - 12 * 60 * 60 * 1000, candidates = walkJsonl(sessionRoot).map(file => ({ file, stat: fs.statSync(file) })).filter(item => item.stat.mtimeMs >= cutoff).sort((a, b) => b.stat.mtimeMs - a.stat.mtimeMs).slice(0, 12), found = []; sessionFiles.clear();
  for (const { file, stat } of candidates) { try { const head = jsonLines(readPart(file, 0, Math.min(stat.size, 131072))), meta = head.find(item => item.type === 'session_meta')?.payload; if (!meta || meta.source === 'exec' || meta.originator === 'codex_exec') continue; const tail = jsonLines(readPart(file, Math.max(0, stat.size - 262144), Math.min(stat.size, 262144))); const events = [...head.slice(0, 3), ...tail]; const active = events.filter(item => item.type === 'event_msg' && ['task_started', 'task_complete'].includes(item.payload?.type)); const lastState = active.at(-1)?.payload?.type; const last = events.at(-1); const message = lastState === 'task_started' ? 'Working…' : lastState === 'task_complete' ? 'Task completed' : last?.payload?.item?.type === 'AgentMessage' ? 'Agent response received' : 'Session updated'; sessionFiles.set(meta.session_id, file); found.push({ id: `local-${meta.session_id}`, threadId: meta.session_id, name: sessionName(meta.session_id), workdir: meta.cwd || 'Local CLI', model: meta.model || 'CLI', source: 'interactive CLI', status: lastState === 'task_started' ? 'running' : 'completed', startedAt: meta.timestamp || stat.birthtime.toISOString(), endedAt: lastState === 'task_complete' ? stat.mtime.toISOString() : null, events: [{ message }], eventCount: 0 }); } catch {} }
  const serialized = JSON.stringify(found); if (serialized !== JSON.stringify(cliSessions.sessions)) { cliSessions.sessions = found; broadcast('sessions', cliSessions); }
}
try { fs.watch(sessionRoot, { recursive: true }, () => setTimeout(scanSessions, 250)); } catch {} setInterval(scanSessions, 1500); scanSessions();
function textFromContent(content) { return (Array.isArray(content) ? content : [content]).map(part => typeof part === 'string' ? part : part?.text || part?.content || '').filter(Boolean).join('\n'); }
function sessionTranscript(sessionId) { const file = sessionFiles.get(sessionId); if (!file || !fs.existsSync(file)) return null; const records = jsonLines(fs.readFileSync(file, 'utf8')), entries = [], seen = new Set(); for (const record of records) { const payload = record.payload || {}; if (record.type === 'response_item' && payload.type === 'message' && ['user', 'assistant'].includes(payload.role)) { const text = textFromContent(payload.content); const key = `${payload.role}:${text}`; if (text && !seen.has(key)) { seen.add(key); entries.push({ role: payload.role, text, at: record.timestamp || null }); } } else if (record.type === 'response_item' && ['function_call', 'function_call_output'].includes(payload.type)) { const text = payload.type === 'function_call' ? `${payload.name || 'tool'}\n${payload.arguments || ''}` : String(payload.output || ''); if (text) entries.push({ role: 'tool', text, at: record.timestamp || null }); } else if (record.type === 'event_msg' && payload.type === 'item_completed' && ['UserMessage', 'AgentMessage'].includes(payload.item?.type)) { const role = payload.item.type === 'UserMessage' ? 'user' : 'assistant', text = textFromContent(payload.item.content), key = `${role}:${text}`; if (text && !seen.has(key)) { seen.add(key); entries.push({ role, text, at: record.timestamp || null }); } } } return entries.slice(-300); }
const localProcesses = { processes: [] };
function scanProcesses() { execFile('powershell.exe', ['-NoProfile', '-NonInteractive', '-Command', 'Get-Process codex -ErrorAction SilentlyContinue | Select-Object Id,ProcessName,StartTime | ConvertTo-Json -Compress'], { windowsHide: true, timeout: 2500 }, (error, stdout) => { if (error && !stdout) return; try { const parsed = JSON.parse(stdout || '[]'), processes = (Array.isArray(parsed) ? parsed : [parsed]).filter(Boolean).map(item => ({ id: item.Id, name: item.ProcessName, startedAt: item.StartTime })); if (JSON.stringify(processes) !== JSON.stringify(localProcesses.processes)) { localProcesses.processes = processes; broadcast('processes', localProcesses); } } catch {} }); }
setInterval(scanProcesses, 3000); scanProcesses();
const server = http.createServer((req, res) => { const url = new URL(req.url, `http://${req.headers.host}`);
  if (req.method === 'GET' && url.pathname === '/events') { res.writeHead(200, { 'Content-Type': 'text/event-stream', 'Cache-Control': 'no-cache', Connection: 'keep-alive' }); res.write(': connected\n\n'); clients.add(res); req.on('close', () => clients.delete(res)); return; }
  if (req.method === 'GET' && url.pathname === '/api/runs') return send(res, 200, [...runs.values()].map(publicRun)); if (req.method === 'GET' && url.pathname === '/api/interactive') return send(res, 200, interactive); if (req.method === 'GET' && url.pathname === '/api/sessions') return send(res, 200, cliSessions); if (req.method === 'GET' && /^\/api\/sessions\/[^/]+\/transcript$/.test(url.pathname)) { const sessionId = decodeURIComponent(url.pathname.split('/')[3]); if (!/^[a-zA-Z0-9-]+$/.test(sessionId)) return send(res, 400, { error: 'Invalid session id.' }); const entries = sessionTranscript(sessionId); return entries ? send(res, 200, { entries }) : send(res, 404, { error: 'Local session transcript not found.' }); } if (req.method === 'GET' && url.pathname === '/api/processes') return send(res, 200, localProcesses);
  if (req.method === 'POST' && url.pathname === '/api/runs') { let body = ''; req.on('data', part => body += part); req.on('end', () => { try { send(res, 201, startRun(JSON.parse(body))); } catch (error) { send(res, 400, { error: error.message }); } }); return; }
  if (req.method === 'POST' && /^\/api\/runs\/[^/]+\/stop$/.test(url.pathname)) { const run = runs.get(url.pathname.split('/')[3]); if (!run || run.status !== 'running') return send(res, 404, { error: 'Active run not found.' }); run.process.kill(); run.status = 'stopped'; run.endedAt = new Date().toISOString(); broadcast('run', publicRun(run)); return send(res, 200, publicRun(run)); }
  const file = path.resolve(root, url.pathname === '/' ? 'index.html' : url.pathname.slice(1)); if (!file.startsWith(root) || !fs.existsSync(file) || fs.statSync(file).isDirectory()) return send(res, 404, 'Not found', 'text/plain'); const types = { '.html': 'text/html; charset=utf-8', '.js': 'text/javascript; charset=utf-8', '.css': 'text/css; charset=utf-8' }; send(res, 200, fs.readFileSync(file), types[path.extname(file)] || 'application/octet-stream');
});
server.listen(4173, '127.0.0.1', () => console.log('Codex Command Center: http://127.0.0.1:4173'));
